# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: GOOS=darwin GOARCH=arm64 go build -o bin/ -v ./...

    - name: Upload to release
      uses: Shopify/upload-to-release@v1.0.1
      with:
        name: my-artifact
        path: bin/cmd
        repo-token: ${{ secrets.GITHUB_TOKEN }}
