name: Release

on:
  push:
    tags:
        - "v*"

permissions:
      contents: write
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: |
        GOOS=darwin GOARCH=arm64 go build -o bin/ -v ./...
        mv bin/cmd bin/tracker-darwin-arm64
        rm bin/cmd
        GOOS=windows GOARCH=amd64 go build -o bin/ -v ./...
        mv bin/cmd.exe bin/tracker-windows-amd64.exe
        rm bin/cmd.exe
        GOOS=linux GOARCH=amd64 go build -o bin/ -v ./...
        mv bin/cmd.exe bin/tracker-linux-amd64.exe
        rm bin/cmd

    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Latest Release"
        files: bin/*
          
    
